### ISSUE TITLE
客户端ID  名称支持中文，或者增加几个备注字段，方便管理

### ISSUE THREAD

**Issue by oslven** [VaalaCat/frp-panel#11]
客户端ID  名称支持中文，或者增加几个备注字段，方便管理,现在使用中文会报错。
time="2024-03-20T18:50:30+08:00" level=info msg="load env file success: .env" func=github.com/VaalaCat/frp-panel/conf.InitConfig file="/home/runner/work/frp-panel/frp-panel/conf/settings.go:73"
time="2024-03-20T18:50:30+08:00" level=info msg="env config rpc host: 127.0.0.1, rpc port: 9001, api host: 127.0.0.1, api port: 9000, api scheme: http" func=main.patchConfig file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/cmd.go:73"
time="2024-03-20T18:50:30+08:00" level=info msg="start to run client" func=main.runClient file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:22"
time="2024-03-20T18:50:30+08:00" level=info msg="start to pull client config, clientID: [admin.c.����]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:16"

**Comment by VaalaCat** [comment]
客户端已支持添加备注
