### ISSUE TITLE
frp服务端安装到windows系统服务中之后怎么卸载

### ISSUE THREAD

**Issue by 1186669517** [VaalaCat/frp-panel#12]
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Ssl3 -bor [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12;set-ExecutionPolicy RemoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1 -OutFile C:install.ps1;powershell.exe C:install.ps1 server -s b1d3e5b1-667a-4405-b0c7-db197c4154c5 -i moying.s.zj -a cc321113415cbcc01766e3ec5b844ab9 -r x.x.x.x -c 9001 -p 9000 -e http
上面这一串，输入到powershell之后 怎么停止其服务

**Comment by VaalaCat** [comment]
C:/frpp/nssm.exe stop frpp
C:/frpp/nssm.exe remove frpp

即可

**Comment by 1186669517** [comment]
> C：/frpp/nssm.exe 停止 frpp C：/frpp/nssm.exe 删除 frpp
> 
> 即可

好的谢谢

**Comment by oslven** [comment]
PS C:\Users\Administrator> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Ssl3 -bor [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12;set-ExecutionPolicy RemoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1 -OutFile C:install.ps1;powershell.exe C:install.ps1 server -s b1d3e5b1-667a-4405-b0c7-db197c4154c5 -i moying.s.zj -a cc321113415cbcc01766e3ec5b844ab9 -r x.x.x.x -c 9001 -p 9000 -e http

执行策略更改
执行策略可帮助你防止执行不信任的脚本。更改执行策略可能会产生安全风险，如 https:/go.microsoft.com/fwlink/?LinkID=135170
中的 about_Execution_Policies 帮助主题所述。是否要更改执行策略?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“N”): a
Invoke-WebRequest : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 228
+ ... emoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/Vaala ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

C:install.ps1 : 无法将“C:install.ps1”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路
径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ C:install.ps1 server -s b1d3e5b1-667a-4405-b0c7-db197c4154c5 -i moyin ...
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:install.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by VaalaCat** [comment]
@oslven 把复制的链接从 `https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1` 变成 `https://mirror.ghproxy.com/https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1`

是你的网络问题

**Comment by oslven** [comment]
> @oslven 把复制的链接从 `https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1` 变成 `https://mirror.ghproxy.com/https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1`
> 
> 是你的网络问题

是我的网络有问题，被墙了
