### ISSUE TITLE
感觉内存管理上好像有问题

### ISSUE THREAD

**Issue by 1186669517** [VaalaCat/frp-panel#17]
长时间运行8天 frp服务端在512mb的机器中内存占用能达到46%，重启服务之后7%，在一台2g内存的机器上运行master端同样上八天，内存大概350mb，占用19%左右

**Comment by 1186669517** [comment]
master端重启之后占用内存约为19mb

**Comment by duncai233** [comment]
我也碰到了

**Comment by VaalaCat** [comment]
程序在运行时会缓存一部分数据，默认设置最大100M，可以通过 `CACHE_SIZE` 配置调节 

https://github.com/VaalaCat/frp-panel/blob/5a952a65c2ec0fb4b841d5cb1636ef93bab936c3/conf/settings.go#L29

**Comment by jsrcode** [comment]
> 程序在运行时会缓存一部分数据，默认设置最大100M，可以通过 `CACHE_SIZE` 配置调节
> 
> https://github.com/VaalaCat/frp-panel/blob/5a952a65c2ec0fb4b841d5cb1636ef93bab936c3/conf/settings.go#L29

服务端长时间运行产生1个多G内存
