### ISSUE TITLE
配置偏移

### ISSUE THREAD

**Issue by duncai233** [VaalaCat/frp-panel#19]
我在客户端八配置的一条隧道,然后将他删除 然后我开了个客户端9 客户端9的隧道会自动同步到客户端8
而且无法删除客户端8的配置,删除完又有 这个是不是数据库的问题？

**Comment by VaalaCat** [comment]
这不是数据库的问题，设计本身是为了在提交出错过后，网页上还能保留之前的填写结果，不用重新填写。

因为造成用户困扰，已经移除该功能

**Comment by duncai233** [comment]
20还是偏移,但是程度会轻了很多
现在更像是幽灵配置
