### ISSUE TITLE
作者大大, 目前0.0.10版本如何支持STCP功能呢

### ISSUE THREAD

**Issue by Sagiri42** [VaalaCat/frp-panel#2]
您好, 作者大大. 这个项目于特别强!!! 我现在有个需求需要使用STCP功能, 请问这个功能要怎么使用呢?
是使用 高级模式 吗? 特别感谢作者大大解答一下!!!!

**Comment by VaalaCat** [comment]
是的，高级模式就是写json格式的frpc.ini就行啦，只需要关注高级模式配置中的proxies和visitors两处
新建两个客户端，内容填下面的就没问题啦，有问题随时在这个issue说吧 @Sagiri42 

高级配置（服务提供方）：
```json
{
  "proxies": [
    {
      "name": "hello_proxy",
      "type": "stcp",
      "secretKey": "abcd",
      "localIP": "127.0.0.1",
      "localPort": 6000
    }
  ]
}
```
高级配置（访问方）：
```json
{
  "visitors": [
    {
        "name": "hello_visitor",
        "type": "stcp",
        "secretKey": "abcd",
        "serverName": "hello_proxy",
        "bindPort": "6001",
        "bindAddr": "127.0.0.1"
    }
  ]
}
```

**Comment by Sagiri42** [comment]
> 是的，高级模式就是写json格式的frpc.ini就行啦，只需要关注高级模式配置中的代理和访客两处 新建两个客户端，内容填下面的就没问题啦，有问题随时在这个issue说吧
> 
> 高级配置（服务提供方）：
> 
> ```json
> {
>   "proxies": [
>     {
>       "name": "hello_proxy",
>       "type": "stcp",
>       "secretKey": "abcd",
>       "localIP": "127.0.0.1",
>       "localPort": 6000
>     }
>   ]
> }
> ```
> 
> 高级配置（访问方）：
> 
> ```json
> {
>   "visitors": [
>     {
>         "name": "hello_visitor",
>         "type": "stcp",
>         "secretKey": "abcd",
>         "serverName": "hello_proxy",
>         "bindPort": "6001",
>         "bindAddr": "127.0.0.1"
>     }
>   ]
> }
> ```

谢谢大佬!!! 超喜欢这个项目!!!
