### ISSUE TITLE
原版frpc

### ISSUE THREAD

**Issue by duncai233** [VaalaCat/frp-panel#24]
希望新增原版frpc配置一键生成

**Comment by VaalaCat** [comment]
不太推荐这样用。原版frp的加密Salt不可修改，本项目为了安全将Salt强制必须自定义修改。如果要兼容的话安全性会有下降

**Comment by duncai233** [comment]
那请问如何使用原版frpc

**Comment by lhw56198** [comment]
> 那请问如何使用原版frpc

大佬，你解决这个问题吗？

**Comment by VaalaCat** [comment]
在运行master时新增一个配置`MASTER_COMPATIBLE_MODE=true`即可

**Comment by 1186669517** [comment]
> 在运行master时新增一个配置即可`MASTER_COMPATIBLE_MODE=true`

如果master修改后已经存在的client端和server端需要做出修改吗

**Comment by duncai233** [comment]
那请问如何获取frpc配置

**Comment by VaalaCat** [comment]
> 如果master修改后已经存在的client端和server端需要做出修改吗

需要重新复制面板中的启动命令启动，如果安装过服务的话需要删掉重新用新命令安装

**Comment by duncai233** [comment]
那能添加个按钮直接下载frpc.josn吗？

**Comment by zhou1050** [comment]
MASTER_COMPATIBLE_MODE=true 功能开启后，所有端口都可以映射了，隧道都不管用
