### ISSUE TITLE
windows报错处理

### ISSUE THREAD

**Issue by lhw56198** [VaalaCat/frp-panel#29]
安装了之后使用windows客户端一直报错，请问佬这个是什么问题呀
time="2024-04-08T17:57:00+08:00" level=error msg="run client error: login to the server failed: dial tcp 0.0.0.0:19000: connectex: No connection could be made because the target machine actively refused it.. With loginFailExit enabled, no additional retries will be attempted" func="github.com/VaalaCat/frp-panel/services/client.(*Client).Run.func2" file="/home/runner/work/frp-panel/frp-panel/services/client/frpc_service.go:118"

**Comment by VaalaCat** [comment]
安装的时候IP地址没有填写正确

**Comment by lhw56198** [comment]
感谢大佬，还想请问一下大佬这个可以用原版的frpc客户端链接吗？

**Comment by VaalaCat** [comment]
参考
#24
