### ISSUE TITLE
功能请求:一个客户端多选隧道

### ISSUE THREAD

**Issue by johncoker233** [VaalaCat/frp-panel#34]
一个隧道不是只能绑一个客户端么?
一个机器要用多个隧道只能多开客户端?
后面能不能客户端能多选隧道?

**Comment by duncai233** [comment]
原版frp允许连接多条隧道

**Comment by duncai233** [comment]
但是不能同时连接多个节点

**Comment by duncai233** [comment]
多节点需要多开客户端 原版的限制

**Comment by johncoker233** [comment]
就是想一个节点多隧道啊，但是后台好像只能选一个

**Comment by VaalaCat** [comment]
一个客户端是可以多隧道的，但多个隧道只能连接到一个服务端。

我猜你指的是一个客户端能连接多个服务端的功能。

这个功能原版没有支持，本项目近期也没有支持的计划

**Comment by johncoker233** [comment]
好吧

**Comment by johncoker233** [comment]
> 一个客户端是可以多隧道的，但多个隧道只能连接到一个服务端。
> 
> 我猜你指的是一个客户端能连接多个服务端的功能。
> 
> 这个功能原版没有支持，本项目近期也没有支持的计划

我的意思是一个客户端链接同一个服务端的多个隧道，不好意思之前没看清楚

**Comment by VaalaCat** [comment]
> > 一个客户端是可以多隧道的，但多个隧道只能连接到一个服务端。
> 
> > 
> 
> > 我猜你指的是一个客户端能连接多个服务端的功能。
> 
> > 
> 
> > 这个功能原版没有支持，本项目近期也没有支持的计划
> 
> 
> 
> 我的意思是一个客户端链接同一个服务端的多个隧道，不好意思之前没看清楚

可以的哈

![image](https://github.com/VaalaCat/frp-panel/assets/42285362/af118494-d0a8-48c9-b4ab-1a367a19927b)
