### ISSUE TITLE
内存管理存在问题

### ISSUE THREAD

**Issue by jsrcode** [VaalaCat/frp-panel#39]
服务端长时间运行产生1个多G内存

**Comment by VaalaCat** [comment]
> 服务端长时间运行产生1个多G内存

请升级到0.21版本，已经修改了内存使用策略

**Comment by duncai233** [comment]
请问新策略是什么？

**Comment by VaalaCat** [comment]
默认只占用10MB数据，之前默认是 百MB级别，外加更频繁释放内存给系统
