### ISSUE TITLE
客户端和服务端分开打包

### ISSUE THREAD

**Issue by oslven** [VaalaCat/frp-panel#4]
客户端和服务端分开打包，方便使用。

**Comment by VaalaCat** [comment]
后续会考虑给客户端单独打一个小号的包，不过服务端的包还是会完整包涵所有功能，方便大规模部署时的版本管理

**Comment by VaalaCat** [comment]
@oslven 已单独打包

**Comment by oslven** [comment]
D:\FRP\frppanel>D:\FRP\frppanel\frp-panel-client-amd64.exe client
time="2024-02-26T09:21:12+08:00" level=info msg="start to run client" func=main.runClient file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:22"
time="2024-02-26T09:21:12+08:00" level=info msg="start to pull client config, clientID: [DESKTOP-50STM3U]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:16"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:30" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config, wait for retry" func=main.initClientOnce file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:60" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run scheduler, interval: 30s" func="github.com/VaalaCat/frp-panel/watcher.(*client).Run" file="/home/runner/work/frp-panel/frp-panel/watcher/client.go:36"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run rpc client" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:95"
time="2024-02-26T09:21:12+08:00" level=info msg="start to regist client to master" func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:29"
time="2024-02-26T09:21:12+08:00" level=info msg="client get server register envent success, clientID: " func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:52"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot receive, sleep 3s and return" func=github.com/VaalaCat/frp-panel/services/rpcclient.RunRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:72" error="rpc error: code = Unknown desc = record not found"
