### ISSUE TITLE
无法删除默认服务端配置吗。

### ISSUE THREAD

**Issue by likesrt** [VaalaCat/frp-panel#41]
删除默认的default服务端配置。刷新后还是存在

**Comment by VaalaCat** [comment]
目前default不允许删除。

default是内置到master中的一个frps，目的是提供最基础的功能

**Comment by likesrt** [comment]
> 目前default不允许删除。
> 
> default是内置到master中的一个frps，目的是提供最基础的功能

谢谢

**Comment by madman163** [comment]
> 目前default不允许删除。
> 
> default是内置到master中的一个frps，目的是提供最基础的功能

那当做server使用,要修改什么,文档没说清楚,不然当前服务器再部署一个server会提示端口已被使用
