### ISSUE TITLE
master报错无法启动server

### ISSUE THREAD

**Issue by zzzzzhy** [VaalaCat/frp-panel#42]
time="2024-05-15T09:18:26Z" level=error msg="cannot recv, sleep 3s and retry" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/app/services/rpcclient/rpc_handler.go:104" error="rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded""
一直报这个错,
启动命令 docker run -d --network=host --restart=unless-stopped -v ./data:/data -e GIN_MODE=release -e MASTER_RPC_HOST=**** -e APP_GLOBAL_SECRET=maintenance vaalacat/frp-panel
直接启动也是一样的,云服务器的问题吗

**Comment by VaalaCat** [comment]
@zzzzzhy 应该是服务器安全组没有开放9000和9001端口

**Comment by zzzzzhy** [comment]
从外部访问是正常的,虚拟机内部访问会卡很久,应该是云服务器的问题
