### ISSUE TITLE
关于 MASTER_RPC_HOST

### ISSUE THREAD

**Issue by lmxslpc** [VaalaCat/frp-panel#46]
MASTER_RPC_HOST这个变量可以用域名么?如果不能那就太不灵活了,frpc本身应该是支持域名访问frps的

还有在docker中什么变量可以定义API控制台端口和rpc端口

**Comment by VaalaCat** [comment]
> MASTER_RPC_HOST这个变量可以用域名么?如果不能那就太不灵活了,frpc本身应该是支持域名访问frps的

是支持域名的

> 还有在docker中什么变量可以定义API控制台端口和rpc端口

API和rpc端口对应
```
MASTER_API_PORT
MASTER_RPC_PORT
```

详细完整的配置参考这里
https://github.com/VaalaCat/frp-panel/blob/main/conf/settings.go

**Comment by lmxslpc** [comment]
nice
