### ISSUE TITLE
客户端报错

### ISSUE THREAD

**Issue by leyung** [VaalaCat/frp-panel#49]
在昨天更新之后，客户端一直报以下错误
`
time="2024-07-22T20:27:36+08:00" level=info msg="start to pull client config, clientID: [admin.c.unraid]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/app/biz/client/rpc_pull_config.go:16"
time="2024-07-22T20:27:36+08:00" level=error msg="cannot load client config" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/app/biz/client/rpc_pull_config.go:41" error="unmarshal ProxyConfig error: plugin type is empty"
`

**Comment by VaalaCat** [comment]
@leyung 请问client和master分别是什么版本呢

**Comment by leyung** [comment]
> @leyung 请问client和master分别是什么版本呢

都是最新版latest

**Comment by VaalaCat** [comment]
@Tylone-zx 看一下这个

**Comment by VaalaCat** [comment]
@leyung 请在面板里重新保存一下这个client的配置。
问题的原因是frp的版本更新到了v0.58.1，配置文件有变动

**Comment by leyung** [comment]
> @leyung 请在面板里重新保存一下这个client的配置。 问题的原因是frp的版本更新到了v0.58.1，配置文件有变动

谢谢，已经可以了
