### ISSUE TITLE
前端的隧道筛选机制问题

### ISSUE THREAD

**Issue by emptinessboy** [VaalaCat/frp-panel#59]
我部署了两个节点和两个客户端，发现A节点和B客户端的隧道配置，会显示在B节点和其他客户端的列表中。容易造成混淆。

另外，通过高级模式修改的JSON（例如配置服务端HTTPS端口），无法保存。虽然系统提示保存成功，但仍会被覆盖。

期待一波后续更新。🤗

**Comment by VaalaCat** [comment]
问题已在12月1日的版本修复
