### ISSUE TITLE
f客户端增加配置文件启动

### ISSUE THREAD

**Issue by oslven** [VaalaCat/frp-panel#6]
ff客户端增加配置文件启动。。

**Comment by oslven** [comment]
增加客户端流量时间控制

**Comment by VaalaCat** [comment]
配置文件启动是指什么呢，可以详细描述一下功能哇

**Comment by oslven** [comment]
不用用那么长的启动命令，把这些放在一个配置文件中，直接从文件获取。

**Comment by VaalaCat** [comment]
@oslven 配置文件启动已支持，启动方式：

在界面上的客户端列表，最右侧的下拉菜单中，选择下载配置文件，将下载的配置文件重命名为 `.env` 注意有一个点在最前面，并且不能有其他后缀名

将配置文件和程序文件放在同一个文件夹，直接启动。例如

```
.
|-- xx                  # 一个文件夹
|   |-- frpp.exe    # 程序文件
|   `-- .env          # 配置文件
```

然后运行

```
frpp.exe client
```

即可

**Comment by oslven** [comment]
D:\FRP\frppanel>D:\FRP\frppanel\frp-panel-client-amd64.exe client
time="2024-02-26T09:21:12+08:00" level=info msg="start to run client" func=main.runClient file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:22"
time="2024-02-26T09:21:12+08:00" level=info msg="start to pull client config, clientID: [DESKTOP-50STM3U]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:16"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:30" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config, wait for retry" func=main.initClientOnce file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:60" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run scheduler, interval: 30s" func="github.com/VaalaCat/frp-panel/watcher.(*client).Run" file="/home/runner/work/frp-panel/frp-panel/watcher/client.go:36"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run rpc client" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:95"
time="2024-02-26T09:21:12+08:00" level=info msg="start to regist client to master" func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:29"
time="2024-02-26T09:21:12+08:00" level=info msg="client get server register envent success, clientID: " func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:52"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot receive, sleep 3s and return" func=github.com/VaalaCat/frp-panel/services/rpcclient.RunRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:72" error="rpc error: code = Unknown desc = record not found"

**Comment by oslven** [comment]
报错了

D:\FRP\frppanel>D:\FRP\frppanel\frp-panel-client-amd64.exe client
time="2024-02-26T09:21:12+08:00" level=info msg="start to run client" func=main.runClient file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:22"
time="2024-02-26T09:21:12+08:00" level=info msg="start to pull client config, clientID: [DESKTOP-50STM3U]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:16"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:30" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config, wait for retry" func=main.initClientOnce file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:60" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run scheduler, interval: 30s" func="github.com/VaalaCat/frp-panel/watcher.(*client).Run" file="/home/runner/work/frp-panel/frp-panel/watcher/client.go:36"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run rpc client" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:95"
time="2024-02-26T09:21:12+08:00" level=info msg="start to regist client to master" func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:29"
time="2024-02-26T09:21:12+08:00" level=info msg="client get server register envent success, clientID: " func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:52"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot receive, sleep 3s and return" func=github.com/VaalaCat/frp-panel/services/rpcclient.RunRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:72" error="rpc error: code = Unknown desc = record not found"

**Comment by oslven** [comment]
报错了
D:\FRP\frppanel>D:\FRP\frppanel\frp-panel-client-amd64.exe client
time="2024-02-26T09:21:12+08:00" level=info msg="start to run client" func=main.runClient file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:22"
time="2024-02-26T09:21:12+08:00" level=info msg="start to pull client config, clientID: [DESKTOP-50STM3U]" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:16"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config" func=github.com/VaalaCat/frp-panel/biz/client.PullConfig file="/home/runner/work/frp-panel/frp-panel/biz/client/rpc_pull_config.go:30" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot pull client config, wait for retry" func=main.initClientOnce file="/home/runner/work/frp-panel/frp-panel/cmd/frppc/client.go:60" error="rpc error: code = Unknown desc = record not found"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run scheduler, interval: 30s" func="github.com/VaalaCat/frp-panel/watcher.(*client).Run" file="/home/runner/work/frp-panel/frp-panel/watcher/client.go:36"
time="2024-02-26T09:21:12+08:00" level=info msg="start to run rpc client" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:95"
time="2024-02-26T09:21:12+08:00" level=info msg="start to regist client to master" func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:29"
time="2024-02-26T09:21:12+08:00" level=info msg="client get server register envent success, clientID: " func=github.com/VaalaCat/frp-panel/services/rpcclient.RegistClientToMaster file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:52"
time="2024-02-26T09:21:12+08:00" level=error msg="cannot receive, sleep 3s and return" func=github.com/VaalaCat/frp-panel/services/rpcclient.RunRPCClient file="/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:72" error="rpc error: code = Unknown desc = record not found"

**Comment by VaalaCat** [comment]
@oslven 请使用0.0.15版本，修复了windows的配置文件加载错误

**Comment by oslven** [comment]
客户端 去掉 client 参数启动

**Comment by VaalaCat** [comment]
@oslven 0.0.16 版本 `frppc` 已移除所有参数，可以直接启动

**Comment by oslven** [comment]
能不改成直接运行exe 不须要在cmd中运行，直接读取当前目录配置文件启动，windows 客户端 可以直接建立服务运行。这样更方便使用，不用再搞vbs cmd.

**Comment by VaalaCat** [comment]
0.0.17版本，已在frppc中实现该功能

**Comment by oslven** [comment]
D:\frpclient>sc create yc binpath= "D:\frpclient\frpclient.exe"  start= auto
D:\frpclient>net start yc
服务没有响应控制功能。

**Comment by VaalaCat** [comment]
我目前没有windows的测试用机器，这个应该是windows的限制，启动路径不太好获取，不建议在服务中直接塞二进制文件。
目前看来双击打开能满足快速启动的要求，很方便能写vbs启动放到服务中了

**Comment by oslven** [comment]
C:\Windows\system32>net start yyyc
服务没有响应控制功能。
  NPS26.1支持这个服务启动。

**Comment by VaalaCat** [comment]
不建议这样操作，windows服务的设计对跨平台开发的程序不友好，请使用面板自带安装的 nssm 操作服务

**Comment by oslven** [comment]
PS C:\Users\Administrator> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Ssl3 -bor [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12;set-ExecutionPolicy RemoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/VaalaCat/frp-panel/main/install.ps1 -OutFile C:install.ps1;powershell.exe C:install.ps1 client -s 95056d10-d9ae-4ca6-b14d-672bfc1935f2 -i admin.c.fdagdsafda -a 6651f85247a8539ff1a71df35945e6a1 -r 127.0.0.1 -c 9001 -p 9000 -e http

执行策略更改
执行策略可帮助你防止执行不信任的脚本。更改执行策略可能会产生安全风险，如 https:/go.microsoft.com/fwlink/?LinkID=135170
中的 about_Execution_Policies 帮助主题所述。是否要更改执行策略?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“N”): A
Invoke-WebRequest : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 228
+ ... emoteSigned;Invoke-WebRequest https://raw.githubusercontent.com/Vaala ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

C:install.ps1 : 无法将“C:install.ps1”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路
径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ C:install.ps1 client -s 95056d10-d9ae-4ca6-b14d-672bfc1935f2 -i admin ...
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:install.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by VaalaCat** [comment]
https://github.com/VaalaCat/frp-panel/issues/12#issuecomment-2014931180

看这里
