### ISSUE TITLE
windwos客户端安装命令中的nssm下载来源好像已经没了

### ISSUE THREAD

**Issue by phyrevue** [VaalaCat/frp-panel#64]
https://github.com/nezhahq/nssm-backup/releases

![Snipaste_2024-10-26_15-40-20](https://github.com/user-attachments/assets/2fbc19f5-e02c-4c96-a535-0dd354bfa0d5)

**Comment by VaalaCat** [comment]
最新的版本已经不需要nssm，升级到最新版即可
