### ISSUE TITLE
Change Repository Language to English

### ISSUE THREAD

**Issue by hamidrabedi** [VaalaCat/frp-panel#66]
Thank you for creating and maintaining this project! It's a valuable tool, and I believe it has the potential to reach a much larger audience.

Currently, the primary language of the repository is Chinese. While this is helpful for Chinese speakers, many users from other parts of the world could benefit from this project if the main language were English.

Could you consider:

Translating the documentation (e.g., README, Wiki) to English?
Updating the UI or other code comments, if applicable, to support English as the default language?
Make sure issues are in English language as well.

This change would help developers from various regions understand, contribute to, and use the project more effectively.

**Comment by VaalaCat** [comment]
As a native Chinese speaker, translating into English may not be my first instinct, but English will undeniably be the most comprehensive choice for the project aside from Chinese.

The README for frp-panel is already available in English here:

https://github.com/VaalaCat/frp-panel/blob/main/README_en.md

The program's UI also includes an i18n translation framework, but translating the content is an extensive task that requires long-term and sustained effort. The file can be found here:

https://github.com/VaalaCat/frp-panel/blob/main/www/lib/i18n.ts

If you are interested, you are more than welcome to participate in the translation work, for which I would be immensely grateful.

**Comment by hamidrabedi** [comment]
Thank you, yes I checked everything and seems like it's all translated.
