### ISSUE TITLE
DOCKER部署服务端，配置后显示离线

### ISSUE THREAD

**Issue by yibohub** [VaalaCat/frp-panel#68]
**描述问题**
DOCKER部署服务端，配置后显示离线
![image](https://github.com/user-attachments/assets/a4a96915-ad8a-4199-b08b-e21b19978412)

![image](https://github.com/user-attachments/assets/bb190370-b7da-438d-a615-359ae09fe26e)
部署的docker-compose文件为：
![image](https://github.com/user-attachments/assets/adb69531-7ebe-4ed3-8591-e5f480a913ca)
这些有什么问题呢？

**Comment by VaalaCat** [comment]
FRPs的监听地址应该写0.0.0.0，尝试重新部署看看呢

**Comment by yibohub** [comment]
还是不行。
![image](https://github.com/user-attachments/assets/170f50d0-1cbf-4669-82e5-b5c9463f5b09)

**Comment by yibohub** [comment]
弄好了。可以正常启动了。

**Comment by yuhaowin** [comment]
@yibohub 请问是怎么修改好的
