### ISSUE TITLE
启动问题 - transport: authentication handshake failed: EOF\

### ISSUE THREAD

**Issue by Longtianmu** [VaalaCat/frp-panel#7]
ERRO[0046]/home/runner/work/frp-panel/frp-panel/services/rpcclient/rpc_handler.go:104 github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient() cannot recv, sleep 3s and retry               error="rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: EOF\""
gRPC证书问题？

**Comment by VaalaCat** [comment]
@Longtianmu 是如何启动的呢，启动的是哪个服务，启动环境也可以发一下

**Comment by Longtianmu** [comment]
重启系统解决了，姑且当作没有吧

**Comment by zzzzzhy** [comment]
time="2024-05-15T09:18:26Z" level=error msg="cannot recv, sleep 3s and retry" func=github.com/VaalaCat/frp-panel/services/rpcclient.StartRPCClient file="/app/services/rpcclient/rpc_handler.go:104" error="rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: context deadline exceeded\""
我也遇到了,一直报这个错,
启动命令 docker run -d --network=host --restart=unless-stopped -v ./data:/data -e GIN_MODE=release  -e MASTER_RPC_HOST=**** -e APP_GLOBAL_SECRET=maintenance vaalacat/frp-panel
