### ISSUE TITLE
关于启动命令参数和面板的bug

### ISSUE THREAD

**Issue by DaseinGeist** [VaalaCat/frp-panel#73]
如果不麻烦的话，我想知道启动命令中-c 9001 -p 9000 -e http部分里-c **-p两个参数的作用，我换成其他端口会产生什么影响？跟“编辑服务端”的“FRPs 监听端口”有什么关系？
在“编辑隧道”时，我发现只能通过高级模式修改本地或者远程端口，直接在方框内修改是不可能的，因为会出现不管删除还是增加内容，方框里面的数字永远能自己改回来的神奇情况。
![image](https://github.com/user-attachments/assets/4be94e0e-f83b-411b-b3a5-e34cac46d383)
，

**Comment by VaalaCat** [comment]
-c是指定连接master对应的http端口
-p是指定连接master对应的rpc端口
换成其他端口需要对应修改master监听的端口，否则会连不上。

无法修改隧道的bug会在下一个版本修复

**Comment by DaseinGeist** [comment]
> -c是指定连接master对应的http端口 -p是指定连接master对应的rpc端口 换成其他端口需要对应修改master监听的端口，否则会连不上。 跟FRPs服务端没有关系
> 
> 我这里没有出现无法修改隧道的情况，修改隧道需要先点击暂存修改，再点击提交变更，否则不会生效

嗯，那我就不懂了，我用docker部署的4.07是这样的，但是换成4.06版本之后就正常了。

**Comment by oXnMe** [comment]
一样的问题，编辑端口和IP，在输入框全选也好，在现有的后面打也好，都不会有内容的变动

**Comment by VaalaCat** [comment]
@oXnMe @DaseinGeist  请更新到v0.0.50或最新的latest版本，已修复该bug
