### ISSUE TITLE
[BUG]编辑隧道配置时前端报错

### ISSUE THREAD

**Issue by ly360** [VaalaCat/frp-panel#74]
**描述问题**
无法添加和修改隧道

**如何复现**
编辑隧道时，添加或修改本地端口、本地IP、远程端口时无法输入

**预期行为**
能正常输入

**安装环境和版本**
- frpp master 软件 版本 v0.0.47
- 安装方式 Docker
- 安装命令 :
docker    run    -d    \
    --network=host    \
    --restart=unless-stopped    \
    -v    $(pwd)/frp-panel:/data    \
    -e    APP_GLOBAL_SECRET=xxx    \
    -e    MASTER_RPC_HOST=xxx    \
    -e MASTER_COMPATIBLE_MODE=true \
    vaalacat/frp-panel

**Comment by VaalaCat** [comment]
@ly360 请更新到v0.0.50或最新的latest版本，已修复该bug
