### ISSUE TITLE
关于隧道展示以及隧道修改逻辑

### ISSUE THREAD

**Issue by likesrt** [VaalaCat/frp-panel#75]
建议以列表形式展示所有隧道，并且直接在列表上修改隧道信息和配置。

http隧道能否配置自定义域名

目前的隧道选择逻辑  当我选择一个服务端  然后选择客户端的时候，会展示当前客户端的全部隧道，无论我选择的服务端是否是该隧道配置的服务端。当我想切换到其他服务端新增隧道时，已有的隧道也会变更为切换的服务端。
我认为正确的应该是，
服务端1-客户端1-隧道1
服务端1-客户端1-隧道2
服务端2-客户端1-隧道3
面板中 应该能单独筛选某一个客户端的所有隧道，或者某一个客户端和某一个服务端的所有隧道。

类似下图

![PixPin_2024-12-15_19-14-02](https://github.com/user-attachments/assets/c9c8400c-a252-4723-9495-9687f97a7085)

#22 
#51

**Comment by likesrt** [comment]
#22 
#51

**Comment by VaalaCat** [comment]
已实现该功能，请使用最新版程序体验
